CREATE TABLE IF NOT EXISTS %table% (
	id			VARCHAR(50),
	class		VARCHAR(50) NOT NULL,
	namespace	VARCHAR(50) NOT NULL,
	description	VARCHAR(100),
	runningPID	MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	runningAt	DATETIME NULL DEFAULT NULL,
	runningBy	INTEGER UNSIGNED NULL DEFAULT NULL,
	lastStatus	VARCHAR(10) NULL DEFAULT NULL,
	lastTime	DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS %table%_run (
	id			VARCHAR(50),
	startedAt	DATETIME NOT NULL,
	startedBy	INTEGER UNSIGNED NULL DEFAULT NULL,
	runningPID	MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_%table%_run__id FOREIGN KEY (id) REFERENCES %table% (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS %table%_logs (
	id			VARCHAR(50),
	startedAt	DATETIME NOT NULL,
	startedBy	INTEGER UNSIGNED NULL DEFAULT NULL,
	execTime	SMALLINT UNSIGNED NOT NULL,
	status		VARCHAR(10) NULL DEFAULT NULL,
	log			BLOB,
	PRIMARY KEY (id),
	CONSTRAINT fk_%table%_logs__id FOREIGN KEY (id) REFERENCES %table% (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
