/* USERS & GROUPS */

CREATE TABLE IF NOT EXISTS t_users (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name	VARCHAR(30) NOT NULL,
	surname	VARCHAR(20),
	email	VARCHAR(30) NULL DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* ACL tables */

CREATE TABLE IF NOT EXISTS t_acl (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	type	ENUM('ACTION', 'FILTER', 'ROLE') NOT NULL,
	code	VARCHAR(40) NOT NULL,
	label	VARCHAR(100) NOT NULL DEFAULT '',
	query	VARCHAR(1024) NULL DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_acl_maps (
	type		ENUM('USER_ROLE', 'USER_ACTION', 'USER_FILTER', 'ROLE_ACTION', 'ROLE_FILTER') NOT NULL,
	user_id		INTEGER UNSIGNED NULL DEFAULT NULL,
	acl_id		INTEGER UNSIGNED NULL DEFAULT NULL,
	data		VARCHAR(1024) NULL DEFAULT NULL,
	UNIQUE KEY uk_t_acl_maps (type, user_id, acl_id),
	CONSTRAINT fk_t_acl_maps__user_id FOREIGN KEY (user_id) REFERENCES t_users (id),
	CONSTRAINT fk_t_acl_maps__acl_id FOREIGN KEY (acl_id) REFERENCES t_acl (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_acl_rules (
	type		ENUM('URL', 'OBJECT', 'ORM') NOT NULL,
	target		VARCHAR(100) NOT NULL,
	method		VARCHAR(40) NULL DEFAULT NULL,
	params_regex VARCHAR(100) NOT NULL,
	acl_id		INTEGER UNSIGNED NOT NULL,
	UNIQUE KEY uk_t_acl_rules (type, target, method),
	CONSTRAINT fk_t_acl_rules__acl_id FOREIGN KEY (acl_id) REFERENCES t_acl (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
