/* USERS & GROUPS */

CREATE TABLE IF NOT EXISTS t_users (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name	VARCHAR(30) NOT NULL,
	surname	VARCHAR(20),
	email	VARCHAR(30) NULL DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_roles (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name	VARCHAR(30) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_u2r (
	user_id		INTEGER UNSIGNED NOT NULL,
	role_id		INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (user_id, role_id),
	CONSTRAINT fk_t_u2r_user FOREIGN KEY (user_id) REFERENCES t_users (id),
	CONSTRAINT fk_t_u2r_role FOREIGN KEY (role_id) REFERENCES t_roles (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* ACL tables */

CREATE TABLE IF NOT EXISTS acl_actions (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	code	VARCHAR(40) NOT NULL,
	label	VARCHAR(100) NOT NULL DEFAULT '',
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS acl_filters (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	code	VARCHAR(40) NOT NULL,
	label	VARCHAR(100) NOT NULL DEFAULT '',
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS acl_filters_sql (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	query	VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS acl (
	type		ENUM('URL', 'OBJECT', 'ORM') NOT NULL,
	target		VARCHAR(100) NOT NULL,
	method		VARCHAR(40) NULL DEFAULT NULL,
	params_regex VARCHAR(100) NOT NULL,
	action		INTEGER UNSIGNED NULL DEFAULT NULL,
	filter		INTEGER UNSIGNED NULL DEFAULT NULL,
	filter_sql	INTEGER UNSIGNED NULL DEFAULT NULL,
	UNIQUE KEY uk_acl (type, target, method),
	CONSTRAINT fk_acl_actions FOREIGN KEY (action) REFERENCES acl_actions (id),
	CONSTRAINT fk_acl_filters FOREIGN KEY (filter) REFERENCES acl_filters (id),
	CONSTRAINT fk_acl_filter_sql FOREIGN KEY (filter_sql) REFERENCES acl_filters_sql (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* ACL mappings */

CREATE TABLE IF NOT EXISTS acl_actions_2_users (
	action_id	INTEGER UNSIGNED NOT NULL,
	user_id		INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (action_id, user_id),
	CONSTRAINT fk_acl_actions_2_users_action FOREIGN KEY (action_id) REFERENCES acl_actions (id) ON DELETE CASCADE,
	CONSTRAINT fk_acl_actions_2_users_user FOREIGN KEY (user_id) REFERENCES t_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS acl_actions_2_roles (
	action_id	INTEGER UNSIGNED NOT NULL,
	role_id	INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (action_id, role_id),
	CONSTRAINT fk_acl_actions_2_roles_action FOREIGN KEY (action_id) REFERENCES acl_actions (id) ON DELETE CASCADE,
	CONSTRAINT fk_acl_actions_2_roles_role FOREIGN KEY (role_id) REFERENCES t_roles (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS acl_filters_2_users (
	filter_id	INTEGER UNSIGNED NOT NULL,
	user_id		INTEGER UNSIGNED NOT NULL,
	data		VARCHAR(50) NOT NULL,
	PRIMARY KEY (filter_id, user_id, data),
	CONSTRAINT fk_acl_filters_2_users_filter FOREIGN KEY (filter_id) REFERENCES acl_filters (id) ON DELETE CASCADE,
	CONSTRAINT fk_acl_filters_2_users_user FOREIGN KEY (user_id) REFERENCES t_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS acl_filters_2_roles (
	filter_id	INTEGER UNSIGNED NOT NULL,
	role_id	INTEGER UNSIGNED NOT NULL,
	data		VARCHAR(50) NOT NULL,
	PRIMARY KEY (filter_id, role_id, data),
	CONSTRAINT fk_acl_filters_2_roles_filter FOREIGN KEY (filter_id) REFERENCES acl_filters (id) ON DELETE CASCADE,
	CONSTRAINT fk_acl_filters_2_roles_role FOREIGN KEY (role_id) REFERENCES t_roles (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
