

CREATE TABLE IF NOT EXISTS t_auth (
	user_id			INT UNSIGNED NOT NULL,
	active			TINYINT(1) NOT NULL DEFAULT 0,
	login			VARCHAR(30) NULL DEFAULT NULL,
	password		VARCHAR(255) NULL DEFAULT NULL,
	passwordExpire	DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (user_id),
	CONSTRAINT uk_t_auth__login UNIQUE KEY (login),
	CONSTRAINT fk_t_auth__user_id FOREIGN KEY (user_id) REFERENCES t_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_tokens (
	type			ENUM('REFRESH', 'REMEMBER', 'RESET') NOT NULL,
	user_id			INT UNSIGNED NOT NULL,
	token			CHAR(64) NOT NULL,
	expire			DATETIME NOT NULL,
	PRIMARY KEY (user_id, token),
	CONSTRAINT fk_t_tokens__user_id FOREIGN KEY (user_id) REFERENCES t_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TRIGGER IF EXISTS triggerAI_t_users;
CREATE TRIGGER triggerAI_t_users AFTER INSERT ON t_users
	FOR EACH ROW BEGIN
		INSERT INTO t_auth (user_id) VALUES (NEW.id);
	END;
